feature/task1
KondrashinMikhail/GoodsWarehouse pull request #1
Opened 2024-04-25 07:54 UTC by KondrashinMikhail

2024-04-25 13:52 UTC, GUR-ok commented
Давай назовем мр "Task1: add price increase scheduling" а не "feature/task1". именно с таким комментарием в итоге смержится сквошнутый коммит в девелоп

2024-04-25 14:00 UTC, GUR-ok requested changes

2024-04-25 14:00 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/aspects/TimeMeasuringAspect.java
> +        log.info("----------------------------------------------------------------------------------");
давай не делать такие прочерки. они замусорят систему агрегации логов

2024-04-25 14:00 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/aspects/TimeMeasuringAspect.java
> +        Object proceed = joinPoint.proceed();
Если joinPoint.proceed(); бросит исключение время замереется?
Мб try {
            return joinPoint.proceed();
        } finally {
			вывести время

2024-04-25 14:00 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/aspects/TimeMeasuringAspect.java
> +@Log4j2
Log4j2 содержит уязвимости и не рекомендуется к использованию. slf4j

2024-04-25 14:00 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/aspects/TransactionalAspect.java
> +        log.info("<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<");
убираем такой лог

2024-04-25 14:00 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/aspects/TransactionalAspect.java
> +        startTime.set(System.currentTimeMillis());
хотелось бы старт таймера от начала работы тела метода, а не от начала коммита

2024-04-25 14:00 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/product/models/entities/Product.java
>  import jakarta.persistence.*;
избегаем схлопнутых импортов. настрой идею плз, чтоб не делала так автоматом

2024-04-25 14:00 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/sheduler/DefaultScheduler.java
> +            double sourcePrice = product.getPrice();
мб переназначение цены в приватный метод и тут лямбду заменить ссылкой на метод this:increasePrice ?

2024-04-25 14:00 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/sheduler/OptimizedScheduler.java
> +            ArrayList<Product> products = productRepository.findAllWithLimit(optimalProductsPart, offset);
Тут главная проблема, что пагинация без сортировки может возвращать одни и те же данные. Ты проверил, цена меняется у всех товаров, а не у части и у некоторых два раза увеличивается? проверь плз селектом в бд после отработки шедулера

2024-04-25 14:00 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/sheduler/OptimizedScheduler.java
> +}
Оставлю здесь для справки
```
package com.crudshop.demo.scheduling;

import com.crudshop.demo.annotation.MeasureExecutionTime;
import jakarta.persistence.EntityManagerFactory;
import lombok.extern.slf4j.Slf4j;
import org.hibernate.Session;
import org.hibernate.jdbc.Work;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnExpression;
import org.springframework.context.annotation.Profile;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

@Component
@Profile("!local")
@ConditionalOnExpression(value = "#{'${app.scheduling.mode:none}'.equals('super')}")
@Slf4j
public class SuperOptimizedScheduler {

    private static final String QUERY = "UPDATE products SET price = price * (1 + ?/100) RETURNING *";

    private final BigDecimal priceIncreasePercentage;

    private final EntityManagerFactory entityManagerFactory;

    public SuperOptimizedScheduler(
            @Value("#{new java.math.BigDecimal(\"${app.scheduling.priceIncreasePercentage:10}\")}")
            BigDecimal priceIncreasePercentage,
            EntityManagerFactory entityManagerFactory
    ) {
        this.priceIncreasePercentage = priceIncreasePercentage;
        this.entityManagerFactory = entityManagerFactory;
    }

    @MeasureExecutionTime
    @Scheduled(fixedDelayString = "${app.scheduling.period}")
    public void increaseProductPrice() {
        log.info("Start SUPER OptimizedProductPriceScheduler");

        final Session session = entityManagerFactory.createEntityManager().unwrap(Session.class);
        try (session) {
            session.doWork(new Work() {
                @Override
                public void execute(final Connection connection) throws SQLException {
                    try (
                            final BufferedWriter fileWriter = new BufferedWriter(new FileWriter("results.txt"));
                            connection
                    ) {
                        connection.setAutoCommit(false);
                        final PreparedStatement preparedStatement = connection.prepareStatement(QUERY);
                        preparedStatement.setBigDecimal(1, priceIncreasePercentage);

                        final ResultSet resultSet = preparedStatement.executeQuery();
                        while (resultSet.next()) {
                            fileWriter.write(buildString(resultSet));
                        }

                        connection.commit();
                    } catch (Exception e) {
                        connection.rollback();
                        throw new RuntimeException(e);
                    }
                }
            });
        }

        log.info("End Super OptimizedProductPriceScheduler");
    }

    private String buildString(final ResultSet resultSet) throws SQLException {
        final StringBuilder builder = new StringBuilder();
        builder.append(resultSet.getString("id"));
        builder.append(" ");
        builder.append(resultSet.getString("name"));
        builder.append(" ");
        builder.append(resultSet.getString("description"));
        builder.append(" ");
        builder.append(resultSet.getString("price"));
        builder.append(" ");
        builder.append(resultSet.getString("article"));

        return builder.toString();
    }
}
```

2024-04-25 14:00 UTC, GUR-ok commented on row_generation/csv_generation_code.png
зачем нам это в мр и репе?

2024-04-25 14:00 UTC, GUR-ok commented
пиши пожалуйста в чатик, что выложил мр.. или мб я упустил

2024-05-02 07:02 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/sheduler/OptimizedScheduler.java
> +            ArrayList<Product> products = productRepository.findAllWithLimit(optimalProductsPart, offset);
Да, я учитывал это, и в query учитывал это, там есть сортировка в запросе
@Query("select p from Product p order by p.id limit :limit offset :offset")

2024-05-02 07:02 UTC, KondrashinMikhail commented on row_generation/csv_generation_code.png
Хотел чтобы хранился скрипт генерации .csv файла, но не хотел чтобы в репозитории был другой язык, я сейчас убрал, у себя этот код сохранил

2024-05-02 07:04 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/sheduler/DefaultScheduler.java
> +            double sourcePrice = product.getPrice();
Исправлено

2024-05-02 07:05 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/product/models/entities/Product.java
>  import jakarta.persistence.*;
Исправлено

2024-05-02 07:05 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/aspects/TransactionalAspect.java
> +        startTime.set(System.currentTimeMillis());
Исправлено

2024-05-02 07:05 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/aspects/TransactionalAspect.java
> +        log.info("<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<");
Исправлено

2024-05-02 07:05 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/aspects/TimeMeasuringAspect.java
> +@Log4j2
Исправлено

2024-05-02 07:05 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/aspects/TimeMeasuringAspect.java
> +        Object proceed = joinPoint.proceed();
Исправлено

2024-05-02 07:05 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/aspects/TimeMeasuringAspect.java
> +        log.info("----------------------------------------------------------------------------------");
Исправлено

2024-05-04 12:02 UTC, GUR-ok approved these changes
ок мерж со сквошем

2024-05-05 05:44 UTC, merged