Task 7: File storage
KondrashinMikhail/GoodsWarehouse pull request #11
Opened 2024-06-12 14:23 UTC by KondrashinMikhail

2024-06-15 12:12 UTC, GUR-ok requested changes

2024-06-15 12:12 UTC, GUR-ok commented on backend/src/main/resources/db/changelog/changeset/006-create-table-image.xml
> +            <column name="path" type="varchar">
по идее нам path не нужен. имя файла мы храним в метадате, все файлы лежат в одном бакете

2024-06-15 12:12 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/controllers/FileStorageController.java
> +    public ResponseEntity<byte[]> getFile(@PathVariable UUID productId) {
Давай byte[] заменим на StreamingResponseBody. Так лучше по памяти по использованию тредов.
Псевдокодный пример как передать outputStream в сервис
```
    @GetMapping("/foo")
    public ResponseEntity<StreamingResponseBody> downloadZip() {
        StreamingResponseBody stream = outputStream-> {
            вызовСервисаДляЗагрузкиАрхива(outputStream);
        };
        
        return ResponseEntity.ok()
            .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=archivename.zip")
            .contentType(MediaType.APPLICATION_OCTET_STREAM)
            .body(stream );
    }
```

Придется outputStream передавать в сервисный метод как аргумент, в этот outputStream и будет записываться zipOutputStream. Т.е. там в конструктор ZipOutputStream передастся outputStream из контроллера

2024-06-15 12:12 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/controllers/FileStorageController.java
> +    @SneakyThrows
@SneakyThrows убираем, в сервисном методе ловим IOException и бросаем сове кастомное, наследованное от runtimeExc

2024-06-15 12:12 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/controllers/FileStorageController.java
> +    public ResponseEntity uploadFile(
тут uuid нужно вернуть айдшник файла

2024-06-15 12:12 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/controllers/FileStorageController.java
> +        String fileName = file.getOriginalFilename();
логику из контроллера вынести в сервис. имя файла пишем в метадату. а ключом для хранения в файловом хранилище будет рандомный uuid. Сейчас к одному товару нельзя прикрепить файлы с одинаковым названием

2024-06-15 12:12 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/controllers/FileStorageController.java
> +    public ResponseEntity<byte[]> getFile(@PathVariable UUID productId) {
тут архив грузим, поэтому нейминг изменить на что-то с zip

2024-06-15 12:12 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/services/filestorage/MinioFileStorageImpl.java
> +    @SneakyThrows
тут тоже @SneakyThrows убираем

2024-06-15 12:12 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/services/filestorage/MinioFileStorageImpl.java
> +    public byte[] getZip(String archiveName, List<Image> images) {
метод станет void, но в аргументы добавится outputStream (который в контроллере получим из StreamingResponseBody. с этим outputStream из аргументов и соберем ZipOutputStream, а не с new FileOutputStream(archiveName)

2024-06-15 12:12 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/services/filestorage/MinioFileStorageImpl.java
> +    public void uploadFile(String path, byte[] content) {
тут возвращаем uuid, принимаем MultipartFile. имя берем из MultipartFile и пишем в метадату, контент тоже из MultipartFile. path не принимаем, айдишник тут генерим

2024-06-21 04:32 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/services/filestorage/MinioFileStorageImpl.java
> +    public byte[] getZip(String archiveName, List<Image> images) {
Исправлено

2024-06-21 04:37 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/controllers/FileStorageController.java
> +    public ResponseEntity<byte[]> getFile(@PathVariable UUID productId) {
Исправил

2024-06-21 04:40 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/controllers/FileStorageController.java
> +    public ResponseEntity<byte[]> getFile(@PathVariable UUID productId) {
Исправлено

2024-06-21 04:43 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/controllers/FileStorageController.java
> +    @SneakyThrows
Исправлено

2024-06-21 04:46 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/services/filestorage/MinioFileStorageImpl.java
> +    @SneakyThrows
Исправлено

2024-06-21 05:30 UTC, KondrashinMikhail commented on backend/src/main/resources/db/changelog/changeset/006-create-table-image.xml
> +            <column name="path" type="varchar">
Исправлено

2024-06-21 05:30 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/controllers/FileStorageController.java
> +    public ResponseEntity uploadFile(
Исправлено

2024-06-21 05:30 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/controllers/FileStorageController.java
> +        String fileName = file.getOriginalFilename();
Исправлено

2024-06-21 05:30 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/services/filestorage/MinioFileStorageImpl.java
> +    public void uploadFile(String path, byte[] content) {
Исправлено

2024-06-23 10:03 UTC, merged