feature/task2
KondrashinMikhail/GoodsWarehouse pull request #2
Opened 2024-04-25 19:06 UTC by KondrashinMikhail

2024-04-27 11:33 UTC, GUR-ok requested changes

2024-04-27 11:33 UTC, GUR-ok commented on backend/pom.xml
> +            <artifactId>javax.servlet-api</artifactId>
зачем эта либа?

2024-04-27 11:33 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/criteria/Condition.java
> +import lombok.*;
импорты принято разворачивать

2024-04-27 11:33 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/criteria/Condition.java
> +    private String operation;
давай сразу десериализовать в енум

2024-04-27 11:33 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/criteria/CriteriaOptions.java
> +    private final String operation;
чтоб сразу десериалозвал
```
package com.crudshop.demo.service.search.enums;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum OperationType {

    EQUAL("="),
    GRATER_THAN_OR_EQ(">="),
    LESS_THAN_OR_EQ("<="),
    LIKE("~");

    private final String code;

    OperationType(String code) {
        this.code = code;
    }

    @JsonValue
    public String getCode() {
        return code;
    }

    @JsonCreator
    public static OperationType fromCode(String code) {
        for (OperationType operationType : OperationType.values()) {
            if (operationType.name().equals(code) || operationType.code.equals(code)) {
                return operationType;
            }
        } return null;
    }
}
```
или вообще так
```
import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonProperty;

public enum OperationType {
    @JsonProperty("operation")
    @JsonAlias({"="})
    EQUAL,

    @JsonProperty("operation")
    @JsonAlias({">="})
    GRATER_THAN_OR_EQ,

    @JsonProperty("operation")
    @JsonAlias({"<="})
    LESS_THAN_OR_EQ,

    @JsonProperty("operation")
    @JsonAlias({"~"})
    LIKE;
}
```

2024-04-27 11:33 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/product/controllers/ProductController.java
> +    @GetMapping("/search")
Грубая ошибка - в GET запросе нельзя реквест боди

2024-04-27 11:33 UTC, GUR-ok commented on backend/src/test/java/mediasoft/ru/backend/product/services/implementations/ProductRepositoryTest.java
> +//                .creationDate(LocalDate.now().minusYears(1))
закоменченый код убираем

2024-04-27 11:33 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/criteria/Condition.java
> +    private String field;
что с валидацией?

2024-04-27 11:33 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/product/services/implementations/ProductServiceImpl.java
> +        if (option.getOperation().equals("~"))
операция будет енумом. не нужно сравнивать со строкой ~

2024-04-27 11:33 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/product/services/implementations/ProductServiceImpl.java
> +        if (valueType == Double.class)
А что если нам для разных Double, например для цены и количества нужно будет разную стратегию сравнения?

2024-04-27 11:33 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/criteria/Condition.java
> +public class Condition {
Давай через интерфейс или абстрактный класс с полиморфной десериализацией. Принимать value не как object, а с конкретным типом в зависимости он названия field. показывал в лекции

2024-05-02 07:45 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/product/services/implementations/ProductServiceImpl.java
> +        if (option.getOperation().equals("~"))
Исправлено

2024-05-02 07:45 UTC, KondrashinMikhail commented on backend/src/test/java/mediasoft/ru/backend/product/services/implementations/ProductRepositoryTest.java
> +//                .creationDate(LocalDate.now().minusYears(1))
Исправлено

2024-05-02 07:45 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/criteria/Condition.java
> +import lombok.*;
Исправлено

2024-05-02 07:46 UTC, KondrashinMikhail commented on backend/pom.xml
> +            <artifactId>javax.servlet-api</artifactId>
Удалена, она была лишняя

2024-05-04 12:02 UTC, GUR-ok commented
переименуй мр плз

2024-05-05 06:19 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/criteria/Condition.java
> +    private String operation;
Исправлено

2024-05-05 06:19 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/criteria/CriteriaOptions.java
> +    private final String operation;
Исправлено

2024-05-05 15:51 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/criteria/Condition.java
> +public class Condition {
Исправлено

2024-05-05 15:51 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/product/services/implementations/ProductServiceImpl.java
> +        if (valueType == Double.class)
Исправлено

2024-05-05 15:52 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/criteria/Condition.java
> +    private String field;
Теперь валидация-это по сути перераспределение на разные объекты

2024-05-05 15:54 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/product/controllers/ProductController.java
> +    @GetMapping("/search")
Исправлено

2024-05-12 06:55 UTC, GUR-ok approved these changes
Давай мержить со сквошем

2024-05-12 08:35 UTC, merged