Task 3: adding currency
KondrashinMikhail/GoodsWarehouse pull request #3
Opened 2024-05-02 19:21 UTC by KondrashinMikhail

…овках запросов для установки поля валют и преобразование цены в зависимости от валюты, хранение в сессии переданной валюты

2024-05-04 12:23 UTC, GUR-ok requested changes
сильно перемудрил с кэшем. и jsonobject непонятно зачем

2024-05-04 12:23 UTC, GUR-ok commented on backend/pom.xml
> +        <dependency>
очень много лишних библиотек. мы не делаем реактивный сервер. достаточно spring-boot-starter-webflux и guava. Ты должен четко ументь объяснить зачем каждая добавляемая либа

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/product/currency/services/implementations/CurrencyServiceClientImpl.java
> +    private String HOST;
Давай больше не будем инжектить через value.
Создай класс для пропертей для rest взаимодействия
@ConfigurationProperties

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/product/currency/services/implementations/CurrencyServiceClientImpl.java
> +    public JSONObject getCurrencyExchangeRate() {
Вместо JSONObject  сделай просто класс.. и получай из вызова объект этого класса. зачем так усложнять.
```
package com.crudshop.demo.currency;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class ExchangeRate {
    private BigDecimal exchangeRateCNY;
    private BigDecimal exchangeRateUSD;
    private BigDecimal exchangeRateEUR;
}
```

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/product/currency/services/implementations/CurrencyServiceClientImpl.java
> +                    .bodyToMono(JSONObject.class)
.bodyToMono(ExchangeRate.class)

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/product/currency/services/implementations/CurrencyServiceClientImpl.java
> +                    .retry(RETRY_COUNT);
здесь .block()

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/product/currency/services/implementations/CurrencyServiceClientImpl.java
> +                    .create(HOST)
webclient сделать бином. через файл конфигурации его создавать. зашить туда хост сразу

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/product/currency/services/implementations/CurrencyServiceClientImpl.java
> +            Mono<JSONObject> response = WebClient
тут моно не будет если вызвать .block() (ниже)

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/product/currency/services/implementations/CurrencyServiceMock.java
> +    public JSONObject getCurrencyExchangeRate() {
JSONObject заменить на свой класс с тремя курсами внутри. все станет элементарно.

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/product/currency/services/implementations/CurrencyServiceMock.java
> +@Slf4j
тут добавить primary и активацию по @ConditionalOnProperty(name = "rest.currency-service.mock.enabled:false")

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/CurrencyCacheConfig.java
> +public class CurrencyCacheConfig {
это в пакет с конфигурациями

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/HeaderCaptureFilter.java
> +            currencyProvider.setCurrency(CurrencyEnum.valueOf(headerValue));
мб попробуем через опшнл
```
        Optional.ofNullable(currency)
           .map(Currency::valueOf)
           .ifPresent(currencyProvider::setCurrency);
```

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/CurrencyProvider.java
> +    CurrencyEnum currency;
тут бы по дефолту сделать рубл.

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/CurrencyProvider.java
> +    CurrencyEnum currency;
private?

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/resources/application.yaml
> +currency-service:
```
rest:
   currency-service:
      host:
      methods: ...
      mock:
         enabled: true
```

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/product/currency/services/implementations/CurrencyServiceMock.java
> +public class CurrencyServiceMock implements CurrencyServiceClient {
при каком условии он создается? почему не возникает конфликта инжекта, тк у тебя два бина реализуют CurrencyServiceClient ?

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/product/models/dto/ProductDTO.java
> +    @Enumerated(EnumType.STRING)
Зачем @Enumerated(EnumType.STRING)?

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/product/models/entities/CurrencyEnum.java
> +    CNY("CNY"),
Зачем создавать еще поле, которое совпадает с названием енума?

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/product/services/implementations/ProductServiceImpl.java
> +    private final CurrencyServiceClientImpl currencyServiceClientImpl;
это плохо
```
 private final CurrencyServiceClientImpl currencyServiceClientImpl;
 private final CurrencyServiceMock currencyServiceMock;
```

должно быть 
```
 private final CurrencyServiceClient currencyServiceClient;
```
Инжектим через интерфейс. В случае несколкьих реализаций, будет инжектиться тот, который primary

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/product/services/implementations/ProductServiceImpl.java
> +    private Boolean CACHE_SERVICE_CONNECTION_ENABLED;
Очень много  @Value везде. не нужно так перегружать все конфигами. возможно просто обойтись константами

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/product/services/implementations/ProductServiceImpl.java
> +    private String CACHE_CURRENCY_NAME;
В productService этого и initializeCurrency вообще быть не должно. кэширование делается просто вешаньем cacheable на метод клиента CurrencyServiceClientImpl. когда в кэше что-то будет лежать, тело метода не будет выполняться и значение курса возьмется из кэша. не понимаю зачем тут столько непонятной логики. писал выше, то нужно создать
```

@Data
@NoArgsConstructor
@AllArgsConstructor
public class ExchangeRate {
    private BigDecimal exchangeRateCNY;
    private BigDecimal exchangeRateUSD;
    private BigDecimal exchangeRateEUR;
}
```

Он будет лежать в кэше и все.

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/product/currency/services/implementations/CurrencyServiceMock.java
> +        if (inputStream == null) throw new IllegalArgumentException("File not found: " + fileName);
мок должен давать рандомные значения. а файл используется для другого. прочитай внимательно задания и посмотри лекцию

2024-05-04 12:23 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/product/services/implementations/ProductServiceImpl.java
> +        initializeCurrency(productDTO);
Нужно сделать обертку, которая по валюте отдает курс. Она обращается сначала к клиенту, а потом читает из файла. Работа с ресурсом файла будет там и работа с CurrencyServiceClient тоже будет там.
Называем класс ExchangeRateProvider
```
@Component
@Slf4j
@RequiredArgsConstructor
public class ExchangeRateProvider {

    private final CurrencyServiceClient currencyServiceClient ;
```
Например имеет

удобный публичный метод, который позволит передать валюту, а в ответ получит курс. не нужно будет в продукт-сервисе много логики городить. Вызвал и все.
```
public BigDecimal getExchangeRate(Currency currency) {
    return Optional.ofNullable(getExchangeRateFromService(currency))
            .orElseGet(() -> getExchangeRateFromFile(currency));
}
```
Сделай два приватных метода. получение валюты из внешнего сервиса и получение из файла
```
private @Nullable BigDecimal getExchangeRateFromService(Currency currency) {
   log.info("Получаем курс из второго сервиса или из кэша");
   return Optional.ofNullable(currencyServiceClient.getExchangeRate())
           .map(rate -> getExchangeRateByCurrency(rate, currency)).orElse(null);
}

private BigDecimal getExchangeRateFromFile(Currency currency) {
...
}

private BigDecimal getExchangeRateByCurrency(ExchangeRate exchangeRate, Currency currency) {
   return switch (currency) {
       case USD -> exchangeRate.getExchangeRateUSD();
       case CNY -> exchangeRate.getExchangeRateCNY();
       case EUR -> exchangeRate.getExchangeRateEUR();
       case RUB -> BigDecimal.ONE;
   };
}
```

2024-05-07 04:39 UTC, KondrashinMikhail commented on backend/pom.xml
> +        <dependency>
Исправлено

2024-05-07 04:55 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/CurrencyProvider.java
> +    CurrencyEnum currency;
Исправлено

2024-05-07 04:56 UTC, KondrashinMikhail commented on backend/src/main/resources/application.yaml
> +currency-service:
Исправлено

2024-05-07 05:02 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/HeaderCaptureFilter.java
> +            currencyProvider.setCurrency(CurrencyEnum.valueOf(headerValue));
Исправлено

2024-05-07 05:03 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/CurrencyProvider.java
> +    CurrencyEnum currency;
Исправлено

2024-05-07 05:06 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/product/currency/services/implementations/CurrencyServiceMock.java
> +    public JSONObject getCurrencyExchangeRate() {
Исправлено

2024-05-07 05:10 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/product/currency/services/implementations/CurrencyServiceClientImpl.java
> +            Mono<JSONObject> response = WebClient
Исправлено

2024-05-07 05:10 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/product/currency/services/implementations/CurrencyServiceClientImpl.java
> +                    .retry(RETRY_COUNT);
Исправлено, до этого .block вызывался ниже

2024-05-07 05:11 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/product/currency/services/implementations/CurrencyServiceClientImpl.java
> +                    .bodyToMono(JSONObject.class)
Исправлено

2024-05-07 05:11 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/product/currency/services/implementations/CurrencyServiceClientImpl.java
> +    public JSONObject getCurrencyExchangeRate() {
Исправлено

2024-05-07 05:12 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/product/models/entities/CurrencyEnum.java
> +    CNY("CNY"),
Оно было для получения значения из JSON-объекта, дубляж был потому что я там просто так назвал поля, но их названия могли поменяться. Сейчас удалил, потому что перешёл на класс

2024-05-07 05:14 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/product/services/implementations/ProductServiceImpl.java
> +    private final CurrencyServiceClientImpl currencyServiceClientImpl;
Исправлено

2024-05-07 05:16 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/product/models/dto/ProductDTO.java
> +    @Enumerated(EnumType.STRING)
Проставил на автомате, как в entity, удалил

2024-05-07 05:16 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/product/currency/services/implementations/CurrencyServiceMock.java
> +public class CurrencyServiceMock implements CurrencyServiceClient {
Исправил

2024-05-07 05:17 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/product/currency/services/implementations/CurrencyServiceMock.java
> +@Slf4j
Исправлено

2024-05-07 05:20 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/CurrencyCacheConfig.java
> +public class CurrencyCacheConfig {
Исправлено

2024-05-07 06:14 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/product/services/implementations/ProductServiceImpl.java
> +    private String CACHE_CURRENCY_NAME;
Да, не до конца понял и не успел разобраться, сейчас понял, замечание исправил

2024-05-07 06:56 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/product/currency/services/implementations/CurrencyServiceClientImpl.java
> +                    .create(HOST)
Исправлено

2024-05-07 06:56 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/product/currency/services/implementations/CurrencyServiceClientImpl.java
> +    private String HOST;
Создал такой класс для этого и для хедеров, так как в application.yaml можно будет указать все кастомные хедеры, и потом брать их из этого property-файла, например, когда надо будет добавлять их в каком-нибудь security-config-е в список разрешённых, или нечто подобное

2024-05-07 06:57 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/product/services/implementations/ProductServiceImpl.java
> +    private Boolean CACHE_SERVICE_CONNECTION_ENABLED;
Исправил, сделал по-больше констант вместо указания через @Value, либо создавал @ConfigurationProperty, но количество конфигов уменьшил

2024-05-07 10:35 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/product/services/implementations/ProductServiceImpl.java
> +        initializeCurrency(productDTO);
Исправлено

2024-05-07 10:36 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/product/currency/services/implementations/CurrencyServiceMock.java
> +        if (inputStream == null) throw new IllegalArgumentException("File not found: " + fileName);
Пересмотрел, исправил

2024-05-12 06:56 UTC, GUR-ok approved these changes
давай тоже подмержим со сквошем

2024-05-13 15:07 UTC, merged