Task 4: adding orders
KondrashinMikhail/GoodsWarehouse pull request #5
Opened 2024-05-09 12:29 UTC by KondrashinMikhail

![Снимок экрана 2024-05-09 в 11 52 39](https://github.com/KondrashinMikhail/GoodsWarehouse/assets/90245664/182f8b4b-8e36-4528-8fb2-38df650a884f)

2024-05-12 07:17 UTC, GUR-ok requested changes
основные проблемы:
- нет связи oneToMany - позволит оптимизировать число запросов, однако нужно следить за n+1 будет.
- множественные селекты по одному айди. нужно получать пачкой

2024-05-12 07:17 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/models/entities/Order.java
> +    @Builder.Default
@Builder.Default я бы убрал.. если хочешь, чтобы энтити по дефолту сейвилась с OrderStatus.CREATED сделай в этом классе метод prepersist

2024-05-12 07:17 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/models/entities/Order.java
> +    private String deliveryAddress;
здесь нужно будет добавить добавить связь oneToMany, о причинах будет в сервисе

2024-05-12 07:17 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/services/order/OrderServiceImpl.java
> +        if (deliveryAddress == null || deliveryAddress.isEmpty() || deliveryAddress.isBlank())
валидацию отсюда убираем. это делается аннотациями над пропертями реквест класса

2024-05-12 07:17 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/services/order/OrderServiceImpl.java
> +            Product product = productService.getEntityById(productInOrderDTO.getId());
ты по каждому товару делаешь селект. по одному айди, нужно запросить разом. причем потом когда их все получишь, нужно собрать хэшмапу, чтобы избежать квадратичной сложности при проходе цикл-в-цикле.
Когда получим все интересующие нас товары создаем мапу
```
        final Map<UUID, ProductEntity> productMap = productList.stream()
                .collect(Collectors.toMap(ProductEntity::getId, Function.identity()));
```    
Потом стримом проходишься по товарам из запроса, внутри обращаясь к этой мапе и создавая orderedProduct

2024-05-12 07:17 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/services/order/OrderServiceImpl.java
> +        return orderMapper.mapModelToCreateOrderResponseDTO(order);
скинь пожалуйста скрин запросов хибернейт после выполнения этого метода. хочу поглядеть как промежуточная таблица с idClass сейвится

2024-05-12 07:17 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/services/order/OrderServiceImpl.java
> +        if (!Objects.equals(order.getCustomer().getId(), customerId))
order.getCustomer().getId() это не даст нам лишний селект запрос в бд? мб поставим     @Fetch(FetchMode.JOIN)
в ордере у кастомера?

2024-05-12 07:17 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/services/order/OrderServiceImpl.java
> +        orderProductRepository.findAllByOrderId(orderId)
тут тоже у тебя будет куча селектов. селект будет для ордера, для каждого orderedProduct и потом еще для каждого product. добавить связь oneToMany в ордер, чтобы тут получить одним запросом типа таким
```
    @Query("""
                select o from OrderEntity o
                left join fetch o.orderedProducts ps
                left join fetch ps.product p
                where o.id = :orderId
           """)
    Optional<OrderEntity> findByIdFetchOrderedProducts(UUID orderId);
```

2024-05-12 07:17 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/services/order/OrderServiceImpl.java
> +                });
приложи скрин плз с селектами до исправления

2024-05-13 15:25 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/services/order/OrderServiceImpl.java
> +        if (deliveryAddress == null || deliveryAddress.isEmpty() || deliveryAddress.isBlank())
Исправлено

2024-05-13 15:26 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/models/entities/Order.java
> +    @Builder.Default
Исправлено

2024-05-13 15:37 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/services/order/OrderServiceImpl.java
> +        if (!Objects.equals(order.getCustomer().getId(), customerId))
Исправлено

2024-05-13 18:47 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/services/order/OrderServiceImpl.java
> +                });
Hibernate: 
    select
        o1_0.id,
        o1_0.customer_id,
        c1_0.id,
        c1_0.is_active,
        c1_0.login,
        c1_0.mail,
        o1_0.delivery_address,
        o1_0.status 
    from
        orders o1_0 
    join
        customer c1_0 
            on c1_0.id=o1_0.customer_id 
    where
        o1_0.id=?
Hibernate: 
    select
        c1_0.id,
        c1_0.is_active,
        c1_0.login,
        c1_0.mail 
    from
        customer c1_0 
    where
        c1_0.id=?
Hibernate: 
    select
        op1_0.order_id,
        op1_0.product_id,
        op1_0.last_modified_date,
        op1_0.product_count,
        op1_0.product_price 
    from
        order_product op1_0 
    left join
        orders o1_0 
            on o1_0.id=op1_0.order_id 
    where
        o1_0.id=?
Hibernate: 
    select
        o1_0.id,
        o1_0.customer_id,
        c1_0.id,
        c1_0.is_active,
        c1_0.login,
        c1_0.mail,
        o1_0.delivery_address,
        o1_0.status 
    from
        orders o1_0 
    join
        customer c1_0 
            on c1_0.id=o1_0.customer_id 
    where
        o1_0.id=?
Hibernate: 
    select
        p1_0.id,
        p1_0.article,
        p1_0.category,
        p1_0.count,
        p1_0.creation_date,
        p1_0.description,
        p1_0.is_available,
        p1_0.last_modified_date,
        p1_0.name,
        p1_0.price 
    from
        product p1_0 
    where
        p1_0.id=?
Hibernate: 
    select
        p1_0.id,
        p1_0.article,
        p1_0.category,
        p1_0.count,
        p1_0.creation_date,
        p1_0.description,
        p1_0.is_available,
        p1_0.last_modified_date,
        p1_0.name,
        p1_0.price 
    from
        product p1_0 
    where
        p1_0.id=?
Hibernate: 
    select
        p1_0.id,
        p1_0.article,
        p1_0.category,
        p1_0.count,
        p1_0.creation_date,
        p1_0.description,
        p1_0.is_available,
        p1_0.last_modified_date,
        p1_0.name,
        p1_0.price 
    from
        product p1_0 
    where
        p1_0.id=?
Hibernate: 
    update
        product 
    set
        article=?,
        category=?,
        count=?,
        description=?,
        is_available=?,
        last_modified_date=?,
        name=?,
        price=? 
    where
        id=?
2024-05-13T22:43:27.887+04:00  INFO 88994 --- [backend] [nio-8080-exec-6] m.r.b.s.product.ProductServiceImpl       : Returned 1.60 products with id - 2ebcc0ac-c982-4127-838b-e7c787a62dae
Hibernate: 
    select
        o1_0.id,
        o1_0.customer_id,
        c1_0.id,
        c1_0.is_active,
        c1_0.login,
        c1_0.mail,
        o1_0.delivery_address,
        o1_0.status 
    from
        orders o1_0 
    join
        customer c1_0 
            on c1_0.id=o1_0.customer_id 
    where
        o1_0.id=?
Hibernate: 
    update
        orders 
    set
        customer_id=?,
        delivery_address=?,
        status=? 
    where
        id=?
        
   Не получилось скрином, там слишком много, не влазит нормально на экран, поэтому так

2024-05-13 18:49 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/services/order/OrderServiceImpl.java
> +        return orderMapper.mapModelToCreateOrderResponseDTO(order);
Hibernate: 
    select
        c1_0.id,
        c1_0.is_active,
        c1_0.login,
        c1_0.mail 
    from
        customer c1_0 
    where
        c1_0.id=?
Hibernate: 
    select
        p1_0.id,
        p1_0.article,
        p1_0.category,
        p1_0.count,
        p1_0.creation_date,
        p1_0.description,
        p1_0.is_available,
        p1_0.last_modified_date,
        p1_0.name,
        p1_0.price 
    from
        product p1_0 
    where
        p1_0.id=?
2024-05-13T22:47:58.119+04:00  INFO 88994 --- [backend] [nio-8080-exec-7] m.r.b.services.order.OrderServiceImpl    : Created order with id - 8a0e4341-c9e9-44e8-9bea-125853e20cf9
Hibernate: 
    select
        op1_0.order_id,
        o1_0.id,
        o1_0.customer_id,
        c1_0.id,
        c1_0.is_active,
        c1_0.login,
        c1_0.mail,
        o1_0.delivery_address,
        o1_0.status,
        op1_0.product_id,
        p1_0.id,
        p1_0.article,
        p1_0.category,
        p1_0.count,
        p1_0.creation_date,
        p1_0.description,
        p1_0.is_available,
        p1_0.last_modified_date,
        p1_0.name,
        p1_0.price,
        op1_0.last_modified_date,
        op1_0.product_count,
        op1_0.product_price 
    from
        order_product op1_0 
    join
        orders o1_0 
            on o1_0.id=op1_0.order_id 
    left join
        customer c1_0 
            on c1_0.id=o1_0.customer_id 
    join
        product p1_0 
            on p1_0.id=op1_0.product_id 
    where
        (
            op1_0.order_id, op1_0.product_id
        ) in ((?, ?))
2024-05-13T22:47:58.125+04:00  INFO 88994 --- [backend] [nio-8080-exec-7] m.r.b.services.order.OrderServiceImpl    : Added product with id - 2ebcc0ac-c982-4127-838b-e7c787a62dae to order with id - 8a0e4341-c9e9-44e8-9bea-125853e20cf9
2024-05-13T22:47:58.126+04:00  INFO 88994 --- [backend] [nio-8080-exec-7] m.r.b.s.product.ProductServiceImpl       : Subtracted 0.5 of product with id - 2ebcc0ac-c982-4127-838b-e7c787a62dae
Hibernate: 
    insert 
    into
        orders
        (customer_id, delivery_address, status, id) 
    values
        (?, ?, ?, ?)
Hibernate: 
    insert 
    into
        order_product
        (last_modified_date, product_count, product_price, order_id, product_id) 
    values
        (?, ?, ?, ?, ?)
Hibernate: 
    update
        product 
    set
        article=?,
        category=?,
        count=?,
        description=?,
        is_available=?,
        last_modified_date=?,
        name=?,
        price=? 
    where
        id=?

2024-05-13 18:50 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/models/entities/Order.java
> +    private String deliveryAddress;
Добавил, изначально хотел обойтись однонаправленной связью, думал по-легче будет

2024-05-13 18:55 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/services/order/OrderServiceImpl.java
> +        orderProductRepository.findAllByOrderId(orderId)
Исправил

2024-05-13 20:38 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/services/order/OrderServiceImpl.java
> +            Product product = productService.getEntityById(productInOrderDTO.getId());
Исправлено здесь и в методе на изменение количества продуктов, ещё поменял в соответствии с этим логику в сервисе по продуктам и немного доработал логику по проверке прав доступа пользователя к заказу

2024-05-20 09:32 UTC, GUR-ok approved these changes
Давай подмержим со сквошем плз

2024-06-08 13:54 UTC, merged