Сложная бизнес-логика
KondrashinMikhail/GoodsWarehouse pull request #9
Opened 2024-06-07 15:45 UTC by KondrashinMikhail

![Снимок экрана 2024-06-07 в 19 39 06](https://github.com/KondrashinMikhail/GoodsWarehouse/assets/90245664/c3612d58-3c81-4e9e-8d13-a22288ff8220)
![Снимок экрана 2024-06-07 в 19 39 15](https://github.com/KondrashinMikhail/GoodsWarehouse/assets/90245664/920194f3-9935-442e-9764-f8a42103df38)
![Снимок экрана 2024-06-07 в 19 39 38](https://github.com/KondrashinMikhail/GoodsWarehouse/assets/90245664/bfa0937e-5a1b-41c2-91f9-2a0996b7bcd8)
![Снимок экрана 2024-06-07 в 19 39 58](https://github.com/KondrashinMikhail/GoodsWarehouse/assets/90245664/549b72f8-fe26-4bb8-87cb-ff0d6c8f2a80)
![Снимок экрана 2024-06-07 в 19 40 21](https://github.com/KondrashinMikhail/GoodsWarehouse/assets/90245664/4c0747d3-061b-4251-972f-a798a0486ea1)

2024-06-08 09:46 UTC, GUR-ok reviewed
По этому мр главная проблема: у тебя 54 файла в измененных, тк он включает в себя изменения из прошлого задания (это посмотреть нереально). Нужно смержить таск 4 (там апрув), потом обновить эту ветку (подмержить в нее актуальный девелоп). Иначе я в этом мр вижу скрипты на создание таблицы orders, кучу эндпоинтов и тд,, что к этой азадче не относится. Трудно отделять новое и то, что уже проверено в прошлых задачах. Актуализируй плз, потом посмотрю.

2024-06-08 09:54 UTC, GUR-ok requested changes

2024-06-08 09:54 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/services/order/OrderServiceImpl.java
> +                .post()
у webClient есть метод toFuture. использовать его

2024-06-08 09:54 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/services/order/OrderServiceImpl.java
> +        accountNumberMap = fetchAccountNumber.join();
join вызывать прям в большом стриме ниже

2024-06-08 09:54 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/services/order/OrderServiceImpl.java
> +        CompletableFuture<Map<String, String>> fetchInn = CompletableFuture.supplyAsync(() -> webClientCrm
для клиентов сделать реализации. мок реализацию и боевую в отдельных классах. Если хочешь сделать через CompletableFuture.supplyAsync(() -> ...)), но внутри клиентов пусть будет block() без toFuture(), но выносить в отдельный класс все равно нужно. Вот этой штуки
```
                .uri(GET_INN_METHOD)
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue(logins)
                .retrieve()
                .bodyToMono(Map.class)
```
тут быть точно не должно. Давай инкапсулируем в класс клиента.

Пример реализации клиентов:
```
/**
 * Реализация клиента сервиса ИНН.
 */
@RequiredArgsConstructor
@Service
public class CrmServiceClientImpl implements CrmServiceClient {
    private final WebClient crmServiceWebClient;
    private final RestConfigurationProperties properties;

    /**
     * Получает данные об ИНН по логинам с использованием WebClient.
     *
     * @param logins логины покупателей.
     * @return Объект {@link Map}, содержащий информацию об ИНН по логинам.
     */
    @Override
    public CompletableFuture<Map<String, String>> getCrms(List<String> logins) {
        return crmServiceWebClient
                .post()
                .uri(properties.crmServiceProperties().getHost() + properties.crmServiceProperties().getMethods().getGetCrm())
                .bodyValue(logins)
                .retrieve()
                .bodyToMono(new ParameterizedTypeReference<Map<String, String>>() {})
                .retry(2)
                .toFuture();
    }
}
```

```
/**
 * Мок-реализация клиента сервиса ИНН.
 */
@Primary
@ConditionalOnProperty(name = "app.rest.crm-service.mock.enabled")
@Component
@Slf4j
public class CrmServiceClientMock implements CrmServiceClient {
    /**
     * Возвращает случайные данные об ИНН.
     *
     * @return Объект {@link CompletableFuture} с случайными данными об ИНН.
     */
    @Override
    public CompletableFuture<Map<String, String>> getCrms(List<String> logins) {
        return CompletableFuture.supplyAsync(() -> {
            Map<String, String> map = new HashMap<>();
            Random random = new Random();
            for (String login : logins) {
                String accountNumber = String.format("%012d", random.nextInt(1000000000));
                map.put(login, accountNumber);
            }
            try {
                Thread.sleep(3000);
            } catch (InterruptedException e) {
                log.error(e.getMessage());
                Thread.currentThread().interrupt();
            }
            return map;
        });
    }
}
```

2024-06-08 09:54 UTC, GUR-ok commented on backend/src/main/java/mediasoft/ru/backend/services/order/OrderServiceImpl.java
> +    @Value("${rest.crm-service.methods.get-inn}")
вынести в отдельные классы проперти. value не используем

2024-06-09 18:26 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/services/order/OrderServiceImpl.java
> +                .post()
Исправлено

2024-06-09 18:26 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/services/order/OrderServiceImpl.java
> +        accountNumberMap = fetchAccountNumber.join();
Исправлено

2024-06-09 18:58 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/services/order/OrderServiceImpl.java
> +    @Value("${rest.crm-service.methods.get-inn}")
Исправлено

2024-06-09 19:42 UTC, KondrashinMikhail commented on backend/src/main/java/mediasoft/ru/backend/services/order/OrderServiceImpl.java
> +        CompletableFuture<Map<String, String>> fetchInn = CompletableFuture.supplyAsync(() -> webClientCrm
Исправлено

2024-06-15 11:59 UTC, GUR-ok approved these changes
Можно подмержить со сквошем

2024-06-15 12:31 UTC, merged